- README.md
If I understand correctly, the type-safe method calls are not available at this moment.
> Remove unavaiable usage from the code snippet in READEME

- scripts/src/public-api-methods.ts
- src/generated/method-types/api_method_types_test.ts
- src/generated/method-types/workflows.ts
Add `workflows.triggers.create` to the `client`.
This will allow an untyped version of `client.workflows.triggers.create`. See example `shortcut` trigger type usage:
```ts
const client = SlackAPI(token, {
slackApiUrl: env["SLACK_API_URL"],
});
await client.workflows.triggers.create({
"type": "shortcut",
"workflow": "#/workflows/send_message", // You should probably pass your own workflow here
"inputs": {
"channel": {
"value": "C013BUS924T", // You should probably pass your own channel here
},
},
"shortcut": {
name: "Send a message",
description: "This will send a message",
},
});
```
> Add the `workflows.triggers.create` method to the client without typing

- src/typed-method-types/apps.ts
Latest Slack β platform `client.apps.datastore.query` method takes `expression_attributes` option instead of `expression_columns`. 
refs: https://api.slack.com/future/datastores#query
An example is shown below:
- Valid type but it does not work
```
let result = await client.apps.datastore.query<typeof MyDatastore.definition>({
datastore: "good_tunes",
expression: "#created = :today",
expression_columns: { "#created": "created"},
expression_values: { ":today": moment().startOf('day').utc().format()}
});
```
- Invalid type but it works fine
```
let result = await client.apps.datastore.query<typeof MyDatastore.definition>({
datastore: "good_tunes",
expression: "#created = :today",
expression_attributes: { "#created": "created"},
expression_values: { ":today": …
```
> Use `expression_attributes` insteads of `expression_columns` in `DatastoreQueryArgs`

- .vscode/settings.json
- src/api-proxy.ts
- src/base-client.ts
- src/types.ts
Currently the SlackAPIClient is being exported as type ```any```, the purpose of these changes is to create a ```SlackAPIClient``` type that will allow it to be passed around more easily.
https://jira.tinyspeck.com/browse/HERMES-3010
> Export slack client

- .github/workflows/deno.yml
- src/base-client.ts
This is the only repo specifying a deno version, so I'm removing the specification so we don't need to switch deno versions to work with this library.
> Change Deno version and run fmt

- .github/workflows/deno.yml
- deno.jsonc
Also use the same deno tasks for testing/formatting/linting as maintainers would in CI
> Add uploading of codecov reports

- src/typed-method-types/workflows/triggers/mod.ts
- src/typed-method-types/workflows/triggers/trigger-filter.ts
- src/typed-method-types/workflows/triggers/trigger-filter_test.ts
- src/typed-method-types/workflows/triggers/webhook.ts
- src/typed-method-types/workflows/triggers/webhook_test.ts
Defines the filter type and uses that filter type in webhook triggers
In order to test this, point your app to this branch (locally or [the raw github url](https://raw.githubusercontent.com/slackapi/deno-slack-api/33940235b6d61ced53f21acd4931d847d2c0006f/src/mod.ts)), instantiate your `client` within a runtime function definition and use `client.workflows.triggers.create` to create a Webhook trigger.
Hopefully typeahead will guide you, but in case you need an example of a valid webhook trigger with a filter, here's one below:
```ts
const client = SlackAPI(token);
await client.workflows.triggers.create({
type: "webhook",
name: "sample event",
workflow: "#/workflows/send_message",
inputs: {},
webhook: {
filter: {
root: {
operator: "OR",
inputs: [{
statement: "3 === 1",
}, {
operator: "AND", …
```
> Add support for filter in webhooks

- src/typed-method-types/workflows/triggers/mod.ts
- src/typed-method-types/workflows/triggers/schedule.ts
- src/typed-method-types/workflows/triggers/scheduled.ts
- src/typed-method-types/workflows/triggers/scheduled_test.ts
- src/typed-method-types/workflows/triggers/webhook_test.ts
This PR adds strict typing based on these two focuses: 
- Separating Scheduled Triggers between a `SingleOccurrenceTriggerSchedule` and a `RecurringTriggerSchedule`
- Separating available frequencies into `DailyFrequencyType`, `WeeklyFrequencyType`, and `MonthlyOrYearlyFrequencyType`
In order to test this, point your app to this branch (locally or [the raw github url](https://raw.githubusercontent.com/slackapi/deno-slack-api/eef11fe/src/mod.ts)), instantiate your client within a runtime function definition and use client.workflows.triggers.create to create a Scheduled trigger.
Hopefully typeahead will guide you, but in case you need an example of a valid Scheduled trigger with frequency, here's one below:
```ts
await client.workflows.triggers.create({
type: "scheduled",
workflow: …
```
> Add specificity to typing for Scheduled Triggers

- src/typed-method-types/workflows/triggers/mod.ts
- src/types.ts
We want to export the type for our triggers so that it can be used in a trigger definition file.
```ts
// trigger.ts file
import { ValidTriggerTypes } from "deno-slack-api/types.ts";
const trigger: ValidTriggerTypes = {
"type": "shortcut",
"name": "Simple trigger",
"workflow": "Example",
"inputs": {
"example1": {
"value": "some string",
},
},
};
```
> Export the valid trigger types

- src/types.ts
Deprecate ValidTriggerTypes export and use Trigger instead
> Deprecate ValidTriggerTypes export and use Trigger instead

- src/typed-method-types/workflows/triggers/scheduled.ts
- src/typed-method-types/workflows/triggers/scheduled_test.ts
Fix a spelling error in scheduled triggers definition
> Fix typo in scheduled triggers definition: occurence -> occurrence

- src/api-proxy_test.ts
- src/api_test.ts
- src/generated/method-types/api_method_types_test.ts
- src/generated/method-types/chat.ts
- src/generated/method-types/functions.ts
- src/generated/method-types/mod.ts
- src/typed-method-types/chat.ts
- src/typed-method-types/functions.ts
- src/typed-method-types/mod.ts
Add the following methods to our list of custom typing:
- `chat.postMessage`
- `functions.completeError`
- `functions.completeSuccess`
Instantiate your `client` within a function and try to use the following methods. They should now provide type-ahead!
```ts
const client = SlackAPI(token);
await client.chat.postMessage({
channel: "",
text: "",
// attachments: [],
// blocks: [],
});
await client.functions.completeSuccess({
function_execution_id: "",
outputs: {},
});
await client.functions.completeError({
error: "",
function_execution_id: ""
})
```
> Add introductory typing to chat.postMessage functions.completeError and functions.completeSuccess

- src/typed-method-types/chat.ts
This adds response typing for `chat.postMessage`
Assign the result of a `chat.postMessage` call to a variable and see what you can access! Compare that to the response logged to the console.
_This is not intended to include all properties from the response, just the important ones_
```ts
const response = await client.chat.postMessage({});
response.ts;
```
> Add a response type for chat.postMessage

- src/api-proxy.ts
- src/api_test.ts
- src/base-client.ts
- src/types.ts
Adds a `setSlackApiUrl()` function to the `BaseClient` class. This is to enable being able to change the `slackApiUrl` value after instantiating a client. This will primarily be helpful in allowing us to provide an instance of the api client in the SDK as a handler param, while still allowing the ability to point the client to a non-default api url.
```ts
const client = SlackApi();
// uses default slack api url of `https://slack.com/api/`
client.apiCall()
client.setSlackApiUrl("https://something.slack.com/api/");
// uses `https://something.slack.com/api/`
client.apiCall();
```
I've added a unit test. This can also be be manually tested by importing this version directly via:
```ts
import { SlackAPI } from "https://raw.githubusercontent.com/slackapi/deno-slack-api/4b8939ead52974351ed15fbd43 …
```
> adding setSlackApiUrl() to BaseClient

- docs/triggers/event-triggers.md
- docs/triggers/link-triggers.md
- docs/triggers/scheduled-trigger.md
- docs/triggers/trigger-basics.md
- docs/triggers/trigger-generic-inputs.md
Added docs on how to use a workflow definition input as a generic for trigger creation.
> Trigger workflow input usage docs

- docs/triggers/scheduled-trigger.md
- src/typed-method-types/workflows/triggers/scheduled.ts
- src/typed-method-types/workflows/triggers/tests/scheduled_test.ts
This PR adds support of additional two new frequency types `once` and `hourly` to schedule triggers
In order to test this, point your app to this branch and instantiate your client within a runtime function definition and use client.workflows.triggers.create to create a Scheduled trigger with either of following configurations:
1. Trigger to run once only 
```
await client.workflows.triggers.create({
type: "scheduled",
workflow: "example",
inputs: {},
name: "example",
schedule: {
start_time: "2022-11-09T7:40:00Z",
timezone: "UTC",
frequency: {
type: "once",
},
},
});
```
or 
```
await client.workflows.triggers.create({
type: "scheduled",
workflow: "example",
inputs: {},
name: "example",
schedule: {
start_time: "2022-11-09T7:40:00Z",
timezone: "UTC",
},
});
```
2. Trigger to run on hourly …
> Added once and hourly scheduled frequency types

- src/typed-method-types/apps.ts
Change the `get` and `delete` methods to use `id` instead of the name of the `primary_key` based on API spec
1. Create a datastore
2. Generate a unique id for the datastore
3. Use `datastore.put` to create a record
4. Chain that record into calls to `datastore.get` and `datastore.delete`
```ts
const getResp = await client.apps.datastore.get<
typeof MyDatastore.definition
>({
datastore: "MyDatastore",
id: uuid, // <-- the line
});
const deleteResp = await client.apps.datastore.delete<
typeof MyDatastore.definition
>({
datastore: "MyDatastore",
id: uuid, // <-- the line
});
```
> Datastore get and delete should use id instead of the name of the primary key

- src/api_test.ts
- src/base-client.ts
- src/typed-method-types/apps.ts
- src/typed-method-types/mod.ts
- src/typed-method-types/typed-method-tests.ts
We are trying to add a typeahead for app.auth.external.get API. This endpoint is used by developers who want to fetch an external token  from Backend using an `external_token_id`.
https://jira.tinyspeck.com/browse/PAX-11446
**Relevant discussion:**
https://slack-pde.slack.com/archives/C02TBKP7CAZ/p1661462028102829?thread_ts=1661456017.960299&cid=C02TBKP7CAZ
**Tests:**
- New tests
- Manually tested in VSCode
> adding types for external.auth.get

- .gitignore
- src/api_test.ts
- src/typed-method-types/apps.ts
- src/typed-method-types/mod.ts
- src/typed-method-types/typed-method-tests.ts
We are trying to add a typeahead for app.auth.external.get API. This endpoint is used by developers who want to fetch an external token  from Backend using an `external_token_id`.
https://jira.tinyspeck.com/browse/PAX-11446
**Relevant discussion:**
https://slack-pde.slack.com/archives/C02TBKP7CAZ/p1661462028102829?thread_ts=1661456017.960299&cid=C02TBKP7CAZ
**Tests:**
- New tests
- Manually tested in VSCode
> Adding more typeaheads

- .github/maintainers_guide.md
- .vscode/settings.json
- deno.jsonc
This is related to the deno-slack-sdk [local environment changes](https://github.com/slackapi/deno-slack-sdk/pull/141)
This applies the same configurations for linting and formatting as the deno-slack-sdk.
RELEASE NOTE: This PR alone does not require a new release!
> Improve lint and format guidelines

- src/api_test.ts
- src/dev_deps.ts
- src/typed-method-types/apps.ts
Update the `DatastoreItem` to only assume that the `primary_key` is provided. This impacts the `put` call's arguments, and the response for the `put`, `get`, and `query` calls.
1. Point your `import_map.json`'s local API version to this one
```json
{
"imports": {
"deno-slack-sdk/": "https://deno.land/x/deno_slack_sdk@1.5.1/",
"deno-slack-api/": "https://raw.githubusercontent.com/slackapi/deno-slack-api/neil-datastores-only-require-primary-key/src/mod.ts"
}
}
```
2. Define a datastore
```ts
export const MyStore = DefineDatastore({
name: "test",
attributes: {
id: { type: Schema.types.string },
email: { type: Schema.types.string },
},
primary_key: "id",
});
```
3. Import `SlackAPI` from the API and instantiate your own client (using the argument from `SlackFunction` will lead to issues) …
> Datastores only require primary key, all other attributes are optional

- src/typed-method-types/apps.ts
- src/typed-method-types/mod.ts
- src/typed-method-types/typed-method-tests.ts
As part of the preparation for datastore general availability, we want to fix a potential confusing behavior of the `datastore.put` method, where it actually behaves more like a field level update (aka patch). The addition of a `apps.datastore.update` route provides a migration path for users when we start handling a `put` as create or replace.
> add apps.datastore.update route

- src/mod.ts
- src/typed-method-types/apps.ts
- src/types.ts
Datastore calls continue to treat response item properties as non-undefined, but export `DatastoreItem` for migration purposes with casting.
Datastore call arguments still treat non `primary_key` properties as optional.
This allows a migration path so that any dev who wants to handle the case where their responses will be undefined can cast their resulting items like
```ts
const responseItem = putResponse.item as DatastoreItem<
typeof MyStore.definition
>;
```
> Export `DatastoreItem` and make Datastore item properties required in responses 

- .gitignore
- deno.jsonc
Small tweak to the coverage task, I think the output is much nicer and it also gives you a project-wide total (which the built-in deno CLI `deno coverage` tool does not):
> Integrate a better CLI utility for generating code coverage reports.

- src/typed-method-types/workflows/triggers/inputs.ts
- src/typed-method-types/workflows/triggers/tests/fixtures/workflows.ts
- src/typed-method-types/workflows/triggers/tests/trigger-workflow_test.ts
Introducing a new WorkflowInput type: `customizable`.
This is part of the [Button starting workflow ](https://corp.quip.com/Jx1JAnkMqaCM#ZIDAAAZVFO2) effort and will allow Next-gen developers to include a `customizable_value` as an input type. We are following Option 2 in the [Link triggers with input tech spec](https://corp.quip.com/6FHSAndrII4w/Options-for-allowing-link-triggers-w-inputs).
Here is the major change in this PR:
```
interface BaseWorkflowInputs {
/** @description The value of the workflow input parameter during workflow execution. Template variables may be used here. */
value?: unknown;
/** @description Set to `true` to allow the input parameter to be customizable, meaning its value is provided separately from the trigger. */
customizable?: true;
}
type WorkflowInputValue …
```
> Introducing a new WorkflowInput type: `customizable`.

- src/typed-method-types/apps.ts
- src/types.ts
Remove features that have the `@deprecated` tag or that were part of our breaking changes announcement.
This includes removing the deprecated `ValidTriggerTypes` named export and properly reflecting that the only attribute that's assured (required) in the response is the `primary_key`. The work to make those attributes optional in the client call was done in a previous PR.
> Remove deprecated features

- docs/triggers/event-triggers.md
- docs/triggers/link-triggers.md
- docs/triggers/scheduled-trigger.md
- docs/triggers/trigger-basics.md
- docs/triggers/trigger-filters.md
- docs/triggers/trigger-generic-inputs.md
- docs/triggers/webhook-triggers.md
- scripts/src/public-api-methods.ts
- src/typed-method-types/workflows/triggers/event.ts
- src/typed-method-types/workflows/triggers/scheduled.ts
- src/typed-method-types/workflows/triggers/tests/event_test.ts
- src/typed-method-types/workflows/triggers/tests/scheduled_test.ts
- src/typed-method-types/workflows/triggers/tests/shortcut_test.ts
- src/typed-method-types/workflows/triggers/tests/webhook_test.ts
- src/typed-method-types/workflows/triggers/webhook.ts
This PR aims to update the project to follow the new Slack Term Glossary, this mainly affect documentation and comments, variable names were left unchanged to avoid breaking changes.
__NOTE__ I think some of this documentation might be duplicated in https://api.slack.com/future/triggers, lmk if we want to remove it from here or make a ticket to remove it
> Update slack naming

- src/typed-method-types/workflows/triggers/event.ts
- src/typed-method-types/workflows/triggers/tests/event_test.ts
This PR sets the `channel_ids` field of the `shared_channel_invite_*` event triggers as optional.
TS error would appear
NOTE: Can't think of a good way to test this since there is no strong type inference
> Shared channel trigger events have optional `channel_ids` 

- src/mod.ts
- src/typed-method-types/workflows/triggers/event-data/dnd_updated.ts
- src/typed-method-types/workflows/triggers/event-data/mod.ts
- src/typed-method-types/workflows/triggers/shortcut-data.ts
- src/typed-method-types/workflows/triggers/tests/context_test.ts
Fast follow changes for the new trigger data enum
- Remove `TriggerContextData` from top level export
- We're planning to introduce `TriggerContext` in a follow-up PR, but we don't want to release `TriggerContextData` in the meantime
- Change from `DNDUpdated` to `DndUpdated` (same for `DndStatus`) to match whats in `trigger-event-types.ts` file
- Update `interactivity` to use the object instead of string reference
- Add tests
> Fast follow changes for the new trigger data enum

- src/mod.ts
- src/typed-method-types/workflows/triggers/mod.ts
We've decided to hold off on enumerating the other parts of TriggerContext in #72 so we're going to just surface `TriggerContextData` directly now
Import this `TriggerContextData` object into your trigger file and attempt to use it in replacement of any use of templatized strings (ex. `"{{data.interactivity}}"`)
```ts
import { Trigger } from "deno-slack-api/types.ts";
import { TriggerContextData, TriggerEventTypes } from "deno-slack-api/mod.ts";
import SubmitIssueWorkflow from "../workflows/submit_issue.ts";
const submitIssue: Trigger<typeof SubmitIssueWorkflow.definition> = {
type: TriggerTypes.Event,
name: "Submit an issue",
description: "Submit an issue to the channel",
workflow: "#/workflows/submit_issue",
event: {
event_type: TriggerEventTypes.ReactionAdded,
channel_ids: …
```
> Export TriggerContextData again

- .github/workflows/npm.yml
- .gitignore
- scripts/build_npm.ts
- src/typed-method-types/workflows/triggers/inputs.ts
In order to prevent failures when creating an npm-compatible build of the deno-slack-sdk repo at the moment of integrating with deno-slack-api, we introduce the npm build in this repo too, to gain earlier awareness about any potential node compatibility issues.
Questions:
> Add a GitHub Action to build this library for npm compatibility.

- src/api_test.ts
- src/base-client-helpers.ts
- src/base-client-helpers_test.ts
- src/base-client.ts
- src/base-client_test.ts
- src/dev_deps.ts
The goal of this PR is to provide slack with a more meaningful `user-agent` information, when users make http requests to Slack.
Previously Deno would populate this header with `Deno/1.x.x` describing the users Deno version, now it will be populated with `Deno/1.x.x OS/<user os> deno-slack-api/<version | undefined>`
- [user os list](https://deno.land/api?s=Deno.build)
The unit tests try to cover all edge cases
Manual testing is tricky since the module must be released in order to get a successful version.
To test an undefined api version use the following to start a local server
```ts
const server = Deno.listen({ port: 8080 });
console.log(`HTTP webserver running.  Access it at:  http://localhost:8080/`);
for await (const conn of server) {
serveHttp(conn);
}
async function serveHttp(conn: …
```
> Update user agent

- src/typed-method-types/apps.ts
- src/typed-method-types/mod.ts
- src/typed-method-types/typed-method-tests.ts
Add support for the experimental bulk APIs
Create an app with a datastore, then use the new bulk APIs to get, put and delete items in bulk
> add datastore bulk apis

- src/typed-method-types/apps.ts
- src/typed-method-types/mod.ts
- src/typed-method-types/typed-method-tests.ts
Add support for [Count API](https://slack-pde.slack.com/archives/C08B6H5U4/p1708545988043419) commands for datastores.
Created an app with a datastore, and used the new API to count the number of items in the datastore.
```
// Example function
export const CountFunctionDefinition = DefineFunction({
callback_id: "count_function",
title: "count function",
description: "Count all rows in datastore",
source_file: "functions/count_function.ts",
input_parameters: {
properties: {
datastore: {
type: Schema.types.string,
description: "Name of datastore to count",
},
},
required: ["datastore"],
}
});
export default SlackFunction(
CountFunctionDefinition,
async ({ client, inputs }) => {
const res = await client.apps.datastore.count({
datastore: inputs.datastore,
});
if (!res.ok) {
const errorMsg = …
```
> feat: Add datastore count API

- .github/maintainers_guide.md
- src/typed-method-types/workflows/triggers/event.ts
- src/typed-method-types/workflows/triggers/tests/event_test.ts
Fixes https://github.com/slackapi/deno-slack-sdk/issues/222 and https://github.com/slackapi/deno-slack-sdk/issues/298
Allows for use of `all_resources: boolean` in a channel event trigger's `event` object. Previously, channel event types _required_ a hard-coded list of `channel_ids` (so were scoped to specific channels by default).
> Add support for wildcard/unscoped channel/workspace event trigger definitions

- src/README.md
`deno task coverage` in the README.md failed.
Compare with [Maintainers_guide.md](https://github.com/slackapi/deno-slack-api/blob/main/.github/maintainers_guide.md).
> docs: fix task coverage cmd

- scripts/src/public-api-methods.ts
- src/generated/method-types/api_method_types_test.ts
- src/generated/method-types/canvases.ts
- src/generated/method-types/conversations.ts
- src/generated/method-types/mod.ts
Also, , no longer consider `functions.*` APIs hidden (since we publicly document them).
> Add new incoming canvas APIs

- src/api-proxy.ts
- src/api-proxy_test.ts
> fix: do not proxy `then`

- src/typed-method-types/workflows/triggers/event-data/channel_archived.ts
- src/typed-method-types/workflows/triggers/event-data/message_posted.ts
- src/typed-method-types/workflows/triggers/event-data/reaction_added.ts
- src/typed-method-types/workflows/triggers/event-data/user_joined_channel.ts
- removes `app_id` from `message_posted` event
- adds `item_user`, `message_link` and `parent_message_link` to `reaction_added` event
- removes `inviter_id` from `user_joined_channel` event
Our public docs on this are here: https://api.slack.com/automation/triggers/event#data
> fix: updating available event trigger data

- .github/workflows/deno.yml
- .github/workflows/npm.yml
- .github/workflows/publish.yml
- .github/workflows/samples.yml
This PR uses the wonderful [`zizmor`](https://github.com/zizmorcore/zizmor) tool to audit our own workflows and [`pinact`](https://github.com/suzuki-shunsuke/pinact) for pinned versioning 👾 
A similar audit can be performed with the `zizmor` tool:
```sh
$ zizmor .
...
No findings to report. Good job! (4 suppressed)
```
> The suppressed findings are expected permission blocks at the top-level of a workflow, but we set this for each job.
🔍 CI covers most cases, but on publish we might want to be aware of possible changes to these workflows.
🎵 🎺 🦖
> ci: pin actions workflow step hashes and use minimum permissions
